# -*- coding: utf-8 -*-
from .forms import LoginForm
import sys
import os
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import login as dlogin
from django.http import JsonResponse


@csrf_exempt
def login(request):
    form = LoginForm(request.POST or None)
    aaaaa = form.is_valid()
    if request.method == 'POST' and form.is_valid():
        user = form.authenticate_user()
        dlogin(request, user)
        sign = request.session

        return render(request, 'signin.html')


@csrf_exempt
def signin(request):
    return render(request, 'signin.html')


@csrf_exempt
def req_test(request):
    json_dict = dict()
    xml_data = '''
    <?xml version="1.0"?>
        <coSpaces total="14">
        <coSpace id="b78b104d-477c-423b-8314-854764a60ba7">
            <name>8091</name>
            <autoGenerated>false</autoGenerated>
            <uri>8091</uri>
            <callId>8091</callId>
        </coSpace>
        <coSpace id="aaa395c5-69ac-4ea4-b4fd-027dce062734">
            <name>8501</name>
            <autoGenerated>false</autoGenerated>
            <uri>8501</uri>
            <callId>8501</callId>
        </coSpace>
        <coSpace id="672e85d4-5cc1-4d90-9b0f-0db0e16cea85">
            <name>9002</name>
            <autoGenerated>false</autoGenerated>
            <uri>9002</uri>
            <callId>9002</callId>
        </coSpace>
        <coSpace id="f524c55b-cbb8-4f12-9b1a-3dde8dcf8b7f">
            <name>9800</name>
            <autoGenerated>false</autoGenerated>
            <uri>9800</uri>
            <callId>9800</callId>
        </coSpace>
        <coSpace id="687796aa-e96f-435d-84d3-2bfe6e532bc4">
            <name>9856</name>
            <autoGenerated>false</autoGenerated>
            <uri>9856</uri>
            <callId>9856</callId>
        </coSpace>
        <coSpace id="5ffb8b34-eb2f-44f5-bc14-84f825c8c65c">
            <name>9865</name>
            <autoGenerated>false</autoGenerated>
            <uri>9865</uri>
            <callId>9865</callId>
        </coSpace>
        <coSpace id="2dc17cd2-632c-41cf-bccc-2265c62bfbaa">
            <name>TMS_Scheduled_Meeting_6000</name>
            <autoGenerated>false</autoGenerated>
            <uri>6000</uri>
            <callId>6000</callId>
        </coSpace>
        <coSpace id="b9287016-8ada-4863-a11f-3b07bd9bcde4">
            <name>TM_기본미팅룸</name>
            <autoGenerated>false</autoGenerated>
            <uri>8991</uri>
            <callId>8991</callId>
        </coSpace>
        <coSpace id="f58c9dcb-180f-435d-9b72-f329610db5da">
            <name>TM_테스트룸</name>
            <autoGenerated>false</autoGenerated>
            <uri>8999</uri>
            <callId>8999</callId>
        </coSpace>
        <coSpace id="fa976ee8-0937-46f9-b39a-506a9f2843af">
            <name>Webex Teams Conference</name>
            <autoGenerated>false</autoGenerated>
            <uri>9001</uri>
            <callId>9001</callId>
        </coSpace>
        <coSpace id="085ef1ce-2f90-4f0e-b563-0500c8356d88">
            <name>test</name>
            <autoGenerated>false</autoGenerated>
            <uri>8011</uri>
            <callId>8011</callId>
        </coSpace>
        <coSpace id="2e2bdc30-36d6-4a1e-ac3f-90b8fa5b13c0">
            <name>uiux</name>
            <autoGenerated>false</autoGenerated>
            <uri>4512</uri>
            <callId>4512</callId>
        </coSpace>
        <coSpace id="14e137be-ca30-467b-90bc-43603236673c">
            <name>마케팅</name>
            <autoGenerated>false</autoGenerated>
            <uri>8010</uri>
            <callId>8010</callId>
        </coSpace>
        <coSpace id="0c3c95fa-3add-431a-9376-73cf3cf0abb3">
            <name>이테크 영상회의</name>
            <autoGenerated>false</autoGenerated>
            <uri>8001</uri>
            <callId>8001</callId>
        </coSpace>
    </coSpaces>
    '''
    json_dict['text'] = xml_data
    json_dict['status_code'] = 200

    return JsonResponse(json_dict)
